version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore PipelineDemo/PipelineDemo.csproj
      install:
        runtime-versions:
            dotnet: 3.1
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output PipelineDemo/PipelineDemo.csproj
artifacts:
  files:
    - PipelineDemo/build_output/**/*
    - scripts/**/*
    - appspec.yml
